### ISSUE TITLE
Sed error during install

### ISSUE THREAD

**Issue by courcelm** [CaronLab/MhcVizPipe#1]
Hello,

I just tried to install MhcVizPipe on Ubuntu 18.04 LTS. I noticed a bunch of errors related to sed:

sed: -e expression #1, char 22: unknown option to `s'

Here is my full install log.

(base) mathieu@protub1-iric:~/mvp$ ./MhcVizPipe_install.sh

MhcVizPipe Installation Utility

This utility will help you install and set up MhcVizPipe on your Mac or Linux computer.

##### Installation Options #####

The default installation directory for MhcVizPipe is:
 /home/mathieu/MhcVizPipe

To install into the default directory, enter y. To specify a different location, enter n.
 [y/n]: y
Default directory selected.

Would you like to add MhcVizPipe to your PATH? This will make it much easier to start the program in the future.
[y/n]: n

Would you like to add NetMHCpan, NetMHCIIpan and GibbsCluster to your PATH? This will make it easier to use these programs in the future. If you have existing installations of these programs, enter n.
[y/n]: n

MhcVizPipe will be installed with the following options:

 Installation directory: /home/mathieu/MhcVizPipe
 Add MhcVizPipe to PATH: false
 Add NetMHCpan, NetMHCIIpan and GibbsCluster to PATH: false
 NetMHCpan version: 4.0

Procced? [y/n]:y

##### Downloading Python bundle #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   689  100   689    0     0   2201      0 --:--:-- --:--:-- --:--:--  2201
100 58.4M  100 58.4M    0     0  33.8M      0  0:00:01  0:00:01 --:--:-- 47.8M

##### Done! #####
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'
sed: -e expression #1, char 22: unknown option to `s'

##### Installing MhcVizPipe #####

Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: wheel
Successfully installed wheel-0.35.1
Collecting MhcVizPipe
  Downloading MhcVizPipe-0.4.5-py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 1.5 MB/s 
Collecting pandas
  Downloading pandas-1.1.2-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 4.6 MB/s 
Collecting seaborn
  Downloading seaborn-0.11.0-py3-none-any.whl (283 kB)
     |████████████████████████████████| 283 kB 34.2 MB/s 
Collecting plotly
  Downloading plotly-4.10.0-py2.py3-none-any.whl (13.0 MB)
     |████████████████████████████████| 13.0 MB 33.1 MB/s 
Collecting numpy
  Downloading numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 23.8 MB/s 
Collecting dominate
  Downloading dominate-2.5.2-py2.py3-none-any.whl (29 kB)
Collecting dash>=1.12.0
  Downloading dash-1.16.0.tar.gz (72 kB)
     |████████████████████████████████| 72 kB 729 kB/s 
Collecting plotly-logo
  Downloading plotly_logo-0.0.2-py3-none-any.whl (10 kB)
Collecting waitress
  Downloading waitress-1.4.4-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.2 MB/s 
Collecting dash-bootstrap-components
  Downloading dash_bootstrap_components-0.10.6-py2.py3-none-any.whl (185 kB)
     |████████████████████████████████| 185 kB 28.5 MB/s 
Collecting upsetplot
  Downloading UpSetPlot-0.4.1.tar.gz (12 kB)
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 27.9 MB/s 
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 41.4 MB/s 
Collecting matplotlib>=2.2
  Downloading matplotlib-3.3.1-cp37-cp37m-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 25.0 MB/s 
Collecting scipy>=1.0
  Downloading scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 51.1 MB/s 
Collecting retrying>=1.3.3
  Downloading retrying-1.3.3.tar.gz (10 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Flask>=1.0.2
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 2.4 MB/s 
Collecting flask-compress
  Downloading Flask-Compress-1.5.0.tar.gz (6.5 kB)
Collecting dash_renderer==1.8.0
  Downloading dash_renderer-1.8.0.tar.gz (950 kB)
     |████████████████████████████████| 950 kB 50.4 MB/s 
Collecting dash-core-components==1.12.0
  Downloading dash_core_components-1.12.0.tar.gz (3.4 MB)
     |████████████████████████████████| 3.4 MB 26.3 MB/s 
Collecting dash-html-components==1.1.1
  Downloading dash_html_components-1.1.1.tar.gz (188 kB)
     |████████████████████████████████| 188 kB 29.7 MB/s 
Collecting dash-table==4.10.1
  Downloading dash_table-4.10.1.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 21.6 MB/s 
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 40.0 MB/s 
Collecting certifi>=2020.06.20
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 44.0 MB/s 
Collecting pillow>=6.2.0
  Downloading Pillow-7.2.0-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 24.4 MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 4.3 MB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 4.7 MB/s 
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 55.1 MB/s 
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 729 kB/s 
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting brotli
  Downloading Brotli-1.0.9-cp37-cp37m-manylinux1_x86_64.whl (357 kB)
     |████████████████████████████████| 357 kB 27.2 MB/s 
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Building wheels for collected packages: dash, upsetplot, retrying, flask-compress, dash-renderer, dash-core-components, dash-html-components, dash-table, future
  Building wheel for dash (setup.py) ... done
  Created wheel for dash: filename=dash-1.16.0-py3-none-any.whl size=82325 sha256=8c8a82f2d63d7c1a095f532c82a024bc05b4b58aadf7a55e26de3abec7cf77c2
  Stored in directory: /home/mathieu/.cache/pip/wheels/cc/68/3c/dc8c9aa36930f5380cf58f261513212e36f8fa759b63585f7c
  Building wheel for upsetplot (setup.py) ... done
  Created wheel for upsetplot: filename=UpSetPlot-0.4.1-py3-none-any.whl size=13118 sha256=5d31dbef7cc766b5000896330be795f2cff19ccb83df8f188c000e0e451ad93a
  Stored in directory: /home/mathieu/.cache/pip/wheels/fa/fa/75/2549bb389f10788afb69643e8bc42cd1516104b2a58a4c1fe8
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11429 sha256=e13dfa76012f42e0d07db93b9353d0f4356597925f8bdbb5bb3cc5b3c06b9f11
  Stored in directory: /home/mathieu/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
  Building wheel for flask-compress (setup.py) ... done
  Created wheel for flask-compress: filename=Flask_Compress-1.5.0-py3-none-any.whl size=5272 sha256=d1c9b0347c8ec4a0fde637afb65a10f99453c3074477eff5b1b9e01b537d59aa
  Stored in directory: /home/mathieu/.cache/pip/wheels/d6/9f/c9/4bf2abf65cceaa8d19423bc34b88443b3b063f167d2082c212
  Building wheel for dash-renderer (setup.py) ... done
  Created wheel for dash-renderer: filename=dash_renderer-1.8.0-py3-none-any.whl size=959342 sha256=1b878520c098511d8ca8a908de5a5e3c36e5e893644b2611050d0e59c26a9b74
  Stored in directory: /home/mathieu/.cache/pip/wheels/40/b5/64/09141cef39aecc7bce0436e12cc5b4ff1698da43fa1e5decdb
  Building wheel for dash-core-components (setup.py) ... done
  Created wheel for dash-core-components: filename=dash_core_components-1.12.0-py3-none-any.whl size=3478749 sha256=09092694929ce0fb17f1a184888967f77499a41ae1af9e35bfa9d385a75ded2d
  Stored in directory: /home/mathieu/.cache/pip/wheels/da/e6/d9/9c2ef00bab380df9224bcafb26f7ba565e784cacc7e9e68157
  Building wheel for dash-html-components (setup.py) ... done
  Created wheel for dash-html-components: filename=dash_html_components-1.1.1-py3-none-any.whl size=427894 sha256=a5beb4aa96680a5ff36b012c3b1ba28c50ec45dccf20250bc2721654fa3d7cd0
  Stored in directory: /home/mathieu/.cache/pip/wheels/c8/a8/46/2900a0845e7992a317eca9ba18e55d47c03ccc4e80d6a37e73
  Building wheel for dash-table (setup.py) ... done
  Created wheel for dash-table: filename=dash_table-4.10.1-py3-none-any.whl size=1824994 sha256=89b04f2e231b31d0191d07eac561f41124bb9d5783ae4f440d888fbbad24fbc1
  Stored in directory: /home/mathieu/.cache/pip/wheels/9b/89/a5/cfba33913363625344b4b3b63a51d958038c8e7b83139e702c
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=d1a4eb6d7548e0c31a3c16a0af48cd6f2aef49853005c921c68abc957e755802
  Stored in directory: /home/mathieu/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built dash upsetplot retrying flask-compress dash-renderer dash-core-components dash-html-components dash-table future
Installing collected packages: pytz, six, python-dateutil, numpy, pandas, certifi, pillow, pyparsing, cycler, kiwisolver, matplotlib, scipy, seaborn, retrying, plotly, dominate, itsdangerous, MarkupSafe, Jinja2, click, Werkzeug, Flask, brotli, flask-compress, dash-renderer, dash-core-components, dash-html-components, dash-table, future, dash, plotly-logo, waitress, dash-bootstrap-components, upsetplot, MhcVizPipe
Successfully installed Flask-1.1.2 Jinja2-2.11.2 MarkupSafe-1.1.1 MhcVizPipe-0.4.5 Werkzeug-1.0.1 brotli-1.0.9 certifi-2020.6.20 click-7.1.2 cycler-0.10.0 dash-1.16.0 dash-bootstrap-components-0.10.6 dash-core-components-1.12.0 dash-html-components-1.1.1 dash-renderer-1.8.0 dash-table-4.10.1 dominate-2.5.2 flask-compress-1.5.0 future-0.18.2 itsdangerous-1.1.0 kiwisolver-1.2.0 matplotlib-3.3.1 numpy-1.19.2 pandas-1.1.2 pillow-7.2.0 plotly-4.10.0 plotly-logo-0.0.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 retrying-1.3.3 scipy-1.5.2 seaborn-0.11.0 six-1.15.0 upsetplot-0.4.1 waitress-1.4.4

##### Downloading data files for netMHCIIpan #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.7M  100 49.7M    0     0  5174k      0  0:00:09  0:00:09 --:--:-- 8956k

Extracting archive... done

##### Downloading data files for netMHCpan4.0 #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.1M  100 24.1M    0     0  4008k      0  0:00:06  0:00:06 --:--:-- 5634k

Extracting archive... done
##### Done! #####

Would you like to delete the temporary files leftover from the installation?
[y/n]: y

Congratulations! MhcVizPipe has been successfully installed!
If you had MhcVizPipe placed in your PATH, you may start it from any terminal by entering the command: MhcVizPipe
Would you like to run MhcVizPipe now?
[y/n]: n

Goodbye!

**Comment by kevinkovalchik** [comment]
Hello!

Thanks for checking it out. These errors happen consistently, but they haven't been affecting the pipeline itself. I looked at that part of the script and figured out was with my separator character in the sed call. I updated the installation script, if you would like to confirm the problem is resolved.

Thanks!
Kevin

**Comment by courcelm** [comment]
I confirm that it is now fixed.
