### ISSUE TITLE
Javascript error: Missing jQuery

### ISSUE THREAD

**Issue by courcelm** [CaronLab/MhcVizPipe#3]
Chrome complains about this on page load.

Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    at Object.jQueryDetection (bootstrap_4.5.0.min.js?m=1600089067.789378:6)
    at bootstrap_4.5.0.min.js?m=1600089067.789378:6
    at bootstrap_4.5.0.min.js?m=1600089067.789378:6
    at bootstrap_4.5.0.min.js?m=1600089067.789378:6

**Comment by kevinkovalchik** [comment]
Strange, it was tested in Chrome. I'll reorder the references.

**Comment by kevinkovalchik** [comment]
Does this happen when the GUI first loads or when generating a report?

**Comment by courcelm** [comment]
On page load

**Comment by kevinkovalchik** [comment]
Ah, I see the error now.

I believe the issue is coming from Dash Bootstrap Components. The only time I am explicitly doing anything with bootstrap.js and jquery is in the reports, and there I am already including jquery before bootstrap.

I explicitly told the app to load jquery, and this seems to be getting it in there before bootstrap. This is in v0.4.7b1 if you want to check it out, or in the master branch.

**Comment by courcelm** [comment]
Install is now broken with this release. See bold parts below:

(base) mathieu@protub1-iric:~/mvp$ ./MhcVizPipe_install.sh

MhcVizPipe Installation Utility

This utility will help you install and set up MhcVizPipe on your Mac or Linux computer.


##### Installation Options #####

The default installation directory for MhcVizPipe is:
 /home/mathieu/MhcVizPipe

To install into the default directory, enter y. To specify a different location, enter n.
 [y/n]: y
Default directory selected.

Would you like to add MhcVizPipe to your PATH? This will make it much easier to start the program in the future.
[y/n]: y

Would you like to add NetMHCpan, NetMHCIIpan and GibbsCluster to your PATH? This will make it easier to use these programs in the future. If you have existing installations of these programs, enter n.
[y/n]: y



MhcVizPipe will be installed with the following options:

 Installation directory: /home/mathieu/MhcVizPipe
 Add MhcVizPipe to PATH: true
 Add NetMHCpan, NetMHCIIpan and GibbsCluster to PATH: true
 NetMHCpan version: 4.0

Procced? [y/n]:y

##### Downloading Python bundle #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   689  100   689    0     0   1701      0 --:--:-- --:--:-- --:--:--  1701
100 58.4M  100 58.4M    0     0  14.3M      0  0:00:04  0:00:04 --:--:-- 18.1M
exit_on_error $? curl -L -o ./temp/python.tar.gz "$URL"

##### Done! #####

##### Extracting Python bundle #####

exit_on_error $? tar -xf ./temp/python.tar.gz --directory "$INSTALL_DIR"

##### Done! #####
### **./MhcVizPipe_install.sh: line 175: !.: event not found**

##### Installing MhcVizPipe #####

Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: wheel
Successfully installed wheel-0.35.1
exit_on_error $? "$INSTALL_DIR"/python/install/bin/python3 -m pip install wheel
Collecting MhcVizPipe
  Using cached MhcVizPipe-0.4.6-py3-none-any.whl (198 kB)
Processing /home/mathieu/.cache/pip/wheels/cc/68/3c/dc8c9aa36930f5380cf58f261513212e36f8fa759b63585f7c/dash-1.16.0-py3-none-any.whl
Collecting pandas
  Using cached pandas-1.1.2-cp37-cp37m-manylinux1_x86_64.whl (10.5 MB)
Collecting plotly
  Using cached plotly-4.10.0-py2.py3-none-any.whl (13.0 MB)
Collecting numpy
  Using cached numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
Processing /home/mathieu/.cache/pip/wheels/fa/fa/75/2549bb389f10788afb69643e8bc42cd1516104b2a58a4c1fe8/UpSetPlot-0.4.1-py3-none-any.whl
Collecting waitress
  Using cached waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Collecting dash-bootstrap-components
  Using cached dash_bootstrap_components-0.10.6-py2.py3-none-any.whl (185 kB)
Collecting plotly-logo
  Using cached plotly_logo-0.0.2-py3-none-any.whl (10 kB)
Collecting seaborn
  Using cached seaborn-0.11.0-py3-none-any.whl (283 kB)
Collecting dominate
  Using cached dominate-2.5.2-py2.py3-none-any.whl (29 kB)
Collecting Flask>=1.0.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Processing /home/mathieu/.cache/pip/wheels/da/e6/d9/9c2ef00bab380df9224bcafb26f7ba565e784cacc7e9e68157/dash_core_components-1.12.0-py3-none-any.whl
Processing /home/mathieu/.cache/pip/wheels/40/b5/64/09141cef39aecc7bce0436e12cc5b4ff1698da43fa1e5decdb/dash_renderer-1.8.0-py3-none-any.whl
Processing /home/mathieu/.cache/pip/wheels/c8/a8/46/2900a0845e7992a317eca9ba18e55d47c03ccc4e80d6a37e73/dash_html_components-1.1.1-py3-none-any.whl
Processing /home/mathieu/.cache/pip/wheels/d6/9f/c9/4bf2abf65cceaa8d19423bc34b88443b3b063f167d2082c212/Flask_Compress-1.5.0-py3-none-any.whl
Processing /home/mathieu/.cache/pip/wheels/9b/89/a5/cfba33913363625344b4b3b63a51d958038c8e7b83139e702c/dash_table-4.10.1-py3-none-any.whl
Processing /home/mathieu/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0/future-0.18.2-py3-none-any.whl
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Processing /home/mathieu/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf/retrying-1.3.3-py3-none-any.whl
Collecting matplotlib>=2.0
  Downloading matplotlib-3.3.2-cp37-cp37m-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 677 kB/s 
Collecting scipy>=1.0
  Using cached scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting click>=5.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting brotli
  Using cached Brotli-1.0.9-cp37-cp37m-manylinux1_x86_64.whl (357 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-7.2.0-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (88 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Installing collected packages: Werkzeug, itsdangerous, click, MarkupSafe, Jinja2, Flask, six, retrying, plotly, dash-core-components, dash-renderer, dash-html-components, brotli, flask-compress, dash-table, future, dash, python-dateutil, pytz, numpy, pandas, pillow, certifi, cycler, pyparsing, kiwisolver, matplotlib, upsetplot, waitress, dash-bootstrap-components, plotly-logo, scipy, seaborn, dominate, MhcVizPipe
^[[B^[[A^[[A^[[ASuccessfully installed Flask-1.1.2 Jinja2-2.11.2 MarkupSafe-1.1.1 MhcVizPipe-0.4.6 Werkzeug-1.0.1 brotli-1.0.9 certifi-2020.6.20 click-7.1.2 cycler-0.10.0 dash-1.16.0 dash-bootstrap-components-0.10.6 dash-core-components-1.12.0 dash-html-components-1.1.1 dash-renderer-1.8.0 dash-table-4.10.1 dominate-2.5.2 flask-compress-1.5.0 future-0.18.2 itsdangerous-1.1.0 kiwisolver-1.2.0 matplotlib-3.3.2 numpy-1.19.2 pandas-1.1.2 pillow-7.2.0 plotly-4.10.0 plotly-logo-0.0.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 retrying-1.3.3 scipy-1.5.2 seaborn-0.11.0 six-1.15.0 upsetplot-0.4.1 waitress-1.4.4
exit_on_error $? "$INSTALL_DIR"/python/install/bin/python3 -m pip install MhcVizPipe

##### Done! #####

##### Installing and configuring third-party tools #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   151  100   151    0     0    364      0 --:--:-- --:--:-- --:--:--   363
100  1702  100  1702    0     0   2586      0 --:--:-- --:--:-- --:--:--  2586
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152  100   152    0     0    392      0 --:--:-- --:--:-- --:--:--   392
100  1498  100  1498    0     0   1413      0  0:00:01  0:00:01 --:--:--  2587
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152  100   152    0     0    426      0 --:--:-- --:--:-- --:--:--   426
100  1457  100  1457    0     0    906      0  0:00:01  0:00:01 --:--:--  1206

##### Downloading data files for netMHCIIpan #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.7M  100 49.7M    0     0  5332k      0  0:00:09  0:00:09 --:--:-- 10.0M

Extracting archive... done

##### Downloading data files for netMHCpan4.0 #####

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.1M  100 24.1M    0     0  4252k      0  0:00:05  0:00:05 --:--:-- 6132k

Extracting archive... done
exit_on_error $? "$INSTALL_DIR/python/install/bin/python3" -m MhcVizPipe.Tools.install_tools "$INSTALL_DIR/tools"
##### Done! #####

**### ./MhcVizPipe_install.sh: line 195: !/bin/bash\n: event not found
chmod: cannot access '/home/mathieu/MhcVizPipe/MhcVizPipe.sh': No such file or directory
grep: !=: No such file or directory
grep: 0: No such file or directory
grep: !=: No such file or directory
grep: 0: No such file or directory
  exit_on_error $? if [[ "$MHCVIZPIPE_TO_PATH" == "true" ]]; then   cp "$INSTALL_DIR"/MhcVizPipe.sh "$INSTALL_DIR"/bin/MhcVizPipe
./MhcVizPipe_install.sh: line 237: syntax error near unexpected token `then'
./MhcVizPipe_install.sh: line 237: `  exit_on_error $? if [[ "$MHCVIZPIPE_TO_PATH" == "true" ]]; then   cp "$INSTALL_DIR"/MhcVizPipe.sh "$INSTALL_DIR"/bin/MhcVizPipe'**

**Comment by kevinkovalchik** [comment]
Oops, sorry. I forgot to push some changes to the installation script. Try it now.

**Comment by courcelm** [comment]
Installation script fixed but still no jquery loaded....

**Comment by courcelm** [comment]
gui.py not updated during the install

**Comment by courcelm** [comment]
Jquery ok after manualy fixing the file.

**Comment by kevinkovalchik** [comment]
Oh, I see that it installed 0.4.6 in your console output above. Because the release is tagged as beta Pip won't use it as the most recent version. If you modify line 174 of the installation script to include `pip install MhcVizPipe==0.4.7b1` it should work the same as when you manually fixed the file.
