### ISSUE TITLE
Broken PATH

### ISSUE THREAD

**Issue by courcelm** [CaronLab/MhcVizPipe#5]
MhcVizPipe broke PATH for other applications.

This is caused by the unnecessary comma.

PATH=/home/mathieu/MhcVizPipe/bin:"$PATH;"

**Comment by kevinkovalchik** [comment]
Should be fixed now. I'm not at my computer at the moment but I'll confirm later this morning.

**Comment by kevinkovalchik** [comment]
It's fixed.

Thanks,
Kevin
