### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by vmd28-97** [CaronLab/MhcVizPipe#6]
I am trying to install MhcVizPipeline on windows operating system I keep on getting directory not found error. 
./MhcVizPipe_install.sh:line175 :/home/abc/MhcVizPipe/Python/install/bin/python3: No such file or directory
I am not able to rectify this please assist.

**Comment by kevinkovalchik** [comment]
Hello,

I have a new version of the tool which uses a different installation process. I will be putting it up as a release soon, but for now I will email you a copy of it to test out. I'll include instructions in the email.

Kevin
