### ISSUE TITLE
No install.sh file

### ISSUE THREAD

**Issue by enric-serra-sanz** [CaronLab/MhcVizPipe#7]
File from readme is not there anymore MhcVizPipe_install.sh.
If you follow the readme it is even more confusing because you get the html for the 404.

**Comment by kevinkovalchik** [comment]
Yikes, sorry. The installation process changed a while ago and doesn't use the MhcVizPipe_install.sh script anymore. The wiki has the correct instructions. Either I forgot to update the readme or I accidentally uploaded an old version. Thanks for bringing this to my attention.

I will update the readme as soon as possible. In the meantime, please see the instructions here: https://github.com/CaronLab/MhcVizPipe/wiki

Let me know if you run into any more issues.

Best wishes,
Kevin
